# Generated by Django 5.2.1 on 2026-04-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsession',
            name='analysis',
        ),
        migrations.AddField(
            model_name='decisionsession',
            name='analysis_cons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='decisionsession',
            name='analysis_pros',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='decisionsession',
            name='analysis_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='decisionsession',
            name='dynamic_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionsession',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed')], default='initiated', max_length=20),
        ),
        migrations.AddField(
            model_name='decisionsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decisionsession',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decisionsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decisioning.category'),
        ),
        migrations.AlterField(
            model_name='decisionsession',
            name='recommendation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='decisionsession',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
