# Generated by Django 4.2.29 on 2026-04-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisioning', '0002_remove_decisionsession_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsession',
            name='analysis_cons',
        ),
        migrations.RemoveField(
            model_name='decisionsession',
            name='analysis_pros',
        ),
    ]
